# Ride Booking Data Cleaning

## 1. Initial Data Inspection

This notebook documents the inspection and cleaning of a public ride booking dataset.

The raw dataset is kept unchanged in the `data/raw/` directory.

The purpose of the initial inspection is to understand the structure and quality of the raw data before making any cleaning decisions.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/Bookings.csv")

## 2. Original Dataset Size

The following check records the number of rows and columns in the raw dataset before any cleaning operations are performed.

In [3]:
df.shape

(103024, 21)

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 103024
Columns: 21

## 3. First Look at the Data

The first five records are displayed to understand the structure and type of information contained in the dataset.

In [5]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [6]:
df.tail()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
103019,2024-07-31 9:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,...,NaN,No,NaN,111,Cash,41,3.6,3.8,#NAME?,NaN
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,...,NaN,No,NaN,1097,UPI,17,4.3,3.3,#NAME?,NaN
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,...,NaN,No,NaN,2201,Cash,37,3.6,3.2,#NAME?,NaN
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,...,NaN,No,NaN,267,UPI,47,3.4,3.1,#NAME?,NaN
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,...,NaN,No,NaN,462,UPI,3,4.8,4.4,#NAME?,NaN

In [7]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images', 'Unnamed: 20'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
 20  Unnamed: 20                 0 non-null       float64
dtypes: float64(5), int64(2), object(14)
memory usage: 16.5+ MB

## 4. Missing Value Analysis

Missing values are inspected before deciding whether values should be removed, filled, or intentionally left missing.

In [9]:
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                 39057
Customer_Rating                39057
Vehicle Images                     0
Unnamed: 20                   103024
dtype: int64

In [10]:
missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percentage
})

missing_report

                            Missing Values  Missing Percentage
Date                                     0            0.000000
Time                                     0            0.000000
Booking_ID                               0            0.000000
Booking_Status                           0            0.000000
Customer_ID                              0            0.000000
Vehicle_Type                             0            0.000000
Pickup_Location                          0            0.000000
Drop_Location                            0            0.000000
V_TAT                                39057           37.910584
C_TAT                                39057           37.910584
Canceled_Rides_by_Customer           92525           89.809171
Canceled_Rides_by_Driver             84590           82.107082
Incomplete_Rides                     39057           37.910584
Incomplete_Rides_Reason              99098           96.189237
Booking_Value                            0            0.000000
Payment_Method                       39057           37.910584
Ride_Distance                            0            0.000000
Driver_Ratings                       39057           37.910584
Customer_Rating                      39057           37.910584
Vehicle Images                           0            0.000000
Unnamed: 20                         103024          100.000000

## 5. Duplicate Record Analysis

Completely duplicated rows are checked to determine whether identical records are present in the raw dataset.

In [11]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [12]:
df.dtypes

Date                           object
Time                           object
Booking_ID                     object
Booking_Status                 object
Customer_ID                    object
Vehicle_Type                   object
Pickup_Location                object
Drop_Location                  object
V_TAT                         float64
C_TAT                         float64
Canceled_Rides_by_Customer     object
Canceled_Rides_by_Driver       object
Incomplete_Rides               object
Incomplete_Rides_Reason        object
Booking_Value                   int64
Payment_Method                 object
Ride_Distance                   int64
Driver_Ratings                float64
Customer_Rating               float64
Vehicle Images                 object
Unnamed: 20                   float64
dtype: object

In [13]:
print("BOOKING STATUS")
print(df["Booking_Status"].value_counts(dropna=False))

print("\nVEHICLE TYPE")
print(df["Vehicle_Type"].value_counts(dropna=False))

print("\nPAYMENT METHOD")
print(df["Payment_Method"].value_counts(dropna=False))

print("\nINCOMPLETE RIDES")
print(df["Incomplete_Rides"].value_counts(dropna=False))

print("\nCANCELED BY CUSTOMER")
print(df["Canceled_Rides_by_Customer"].value_counts(dropna=False))

print("\nCANCELED BY DRIVER")
print(df["Canceled_Rides_by_Driver"].value_counts(dropna=False))

BOOKING STATUS
Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

VEHICLE TYPE
Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

PAYMENT METHOD
Payment_Method
NaN            39057
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

INCOMPLETE RIDES
Incomplete_Rides
No     60041
NaN    39057
Yes     3926
Name: count, dtype: int64

CANCELED BY CUSTOMER
Canceled_Rides_by_Customer
NaN                                             92525
Driver is not moving towards pickup location     3175
Driver asked to cancel                           2670
Change of plans                                  2081
AC is Not working                                1568
Wrong Address                                    1005
Name: count, dtype: int64

CANCELED BY DRIVER
Canceled_Rides_by_Driver
NaN                                    84590
Personal & Car related issue            6542
Customer related issue                  5413
Customer was coughing/sick              3654
More than permitted people in there     2825
Name: count, dtype: int64

In [14]:
print(df["Vehicle Images"].value_counts(dropna=False))

Vehicle Images
#NAME?    103024
Name: count, dtype: int64

In [15]:
print("V_TAT")
print(df["V_TAT"].describe())

print("\nC_TAT")
print(df["C_TAT"].describe())

print("\nBOOKING VALUE")
print(df["Booking_Value"].describe())

print("\nRIDE DISTANCE")
print(df["Ride_Distance"].describe())

print("\nDRIVER RATINGS")
print(df["Driver_Ratings"].describe())

print("\nCUSTOMER RATING")
print(df["Customer_Rating"].describe())

V_TAT
count    63967.000000
mean       170.876952
std         80.803640
min         35.000000
25%         98.000000
50%        168.000000
75%        238.000000
max        308.000000
Name: V_TAT, dtype: float64

C_TAT
count    63967.000000
mean        84.873372
std         36.005100
min         25.000000
25%         55.000000
50%         85.000000
75%        115.000000
max        145.000000
Name: C_TAT, dtype: float64

BOOKING VALUE
count    103024.000000
mean        548.751883
std         536.541221
min         100.000000
25%         242.000000
50%         386.000000
75%         621.000000
max        2999.000000
Name: Booking_Value, dtype: float64

RIDE DISTANCE
count    103024.000000
mean         14.189927
std          15.776270
min           0.000000
25%           0.000000
50%           8.000000
75%          26.000000
max          49.000000
Name: Ride_Distance, dtype: float64

DRIVER RATINGS
count    63967.000000
mean         3.997457
std          0.576834
min          3.000000
25%          3.500000
50%          4.000000
75%          4.500000
max          5.000000
Name: Driver_Ratings, dtype: float64

CUSTOMER RATING
count    63967.000000
mean         3.998313
std          0.578957
min          3.000000
25%          3.500000
50%          4.000000
75%          4.500000
max          5.000000
Name: Customer_Rating, dtype: float64

In [16]:
print(df["Date"].head(10).to_string())

0    2024-07-26 14:00:00
1    2024-07-25 22:20:00
2    2024-07-30 19:59:00
3     2024-07-22 3:15:00
4     2024-07-02 9:02:00
5     2024-07-13 4:42:00
6     2024-07-23 9:51:00
7    2024-07-11 11:12:00
8    2024-07-01 19:19:00
9     2024-07-18 1:31:00

In [17]:
print(df["Time"].head(10).to_string())

0    14:00:00
1    22:20:00
2    19:59:00
3    03:15:00
4    09:02:00
5    04:42:00
6    09:51:00
7    11:12:00
8    19:19:00
9    01:31:00

In [18]:
print("Duplicate Booking IDs:", df["Booking_ID"].duplicated().sum())

Duplicate Booking IDs: 0

In [19]:
print("Rows with cancellation reason but not customer-cancelled:")
print(
    ((df["Canceled_Rides_by_Customer"].notna()) &
     (df["Booking_Status"] != "Canceled by Customer")).sum()
)

print("\nRows with cancellation reason but not driver-cancelled:")
print(
    ((df["Canceled_Rides_by_Driver"].notna()) &
     (df["Booking_Status"] != "Canceled by Driver")).sum()
)

print("\nRows marked incomplete but not successful:")
print(
    ((df["Incomplete_Rides"].notna()) &
     (df["Booking_Status"] != "Success")).sum()
)

Rows with cancellation reason but not customer-cancelled:
0

Rows with cancellation reason but not driver-cancelled:
0

Rows marked incomplete but not successful:
0

In [20]:
cleaned_df = df.copy()

print("Original rows:", len(df))
print("Cleaning dataframe rows:", len(cleaned_df))

Original rows: 103024
Cleaning dataframe rows: 103024

In [21]:
cleaned_df["Date"] = pd.to_datetime(cleaned_df["Date"])

print(cleaned_df["Date"].dtype)

datetime64[ns]

In [22]:
cleaned_df = cleaned_df.drop(columns=["Unnamed: 20"])

print("Columns after removing empty column:", len(cleaned_df.columns))

Columns after removing empty column: 20

In [23]:
cleaned_df = cleaned_df.drop(columns=["Vehicle Images"])

print("Columns after removing unusable column:", len(cleaned_df.columns))

Columns after removing unusable column: 19

In [24]:
cleaned_df.shape

(103024, 19)

In [25]:
cleaned_df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
dtype: object

In [26]:
cleaned_df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [27]:
cleaned_df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0

In [28]:
print("Non-successful bookings:")
print((cleaned_df["Booking_Status"] != "Success").sum())

print("\nMissing V_TAT in non-successful bookings:")
print(
    cleaned_df.loc[
        cleaned_df["Booking_Status"] != "Success", "V_TAT"
    ].isna().sum()
)

print("\nMissing C_TAT in non-successful bookings:")
print(
    cleaned_df.loc[
        cleaned_df["Booking_Status"] != "Success", "C_TAT"
    ].isna().sum()
)

print("\nMissing Driver Ratings in non-successful bookings:")
print(
    cleaned_df.loc[
        cleaned_df["Booking_Status"] != "Success", "Driver_Ratings"
    ].isna().sum()
)

print("\nMissing Customer Ratings in non-successful bookings:")
print(
    cleaned_df.loc[
        cleaned_df["Booking_Status"] != "Success", "Customer_Rating"
    ].isna().sum()
)

Non-successful bookings:
39057

Missing V_TAT in non-successful bookings:
39057

Missing C_TAT in non-successful bookings:
39057

Missing Driver Ratings in non-successful bookings:
39057

Missing Customer Ratings in non-successful bookings:
39057

In [29]:
categorical_na_columns = [
    "Canceled_Rides_by_Customer",
    "Canceled_Rides_by_Driver",
    "Incomplete_Rides",
    "Incomplete_Rides_Reason",
    "Payment_Method"
]

for column in categorical_na_columns:
    cleaned_df[column] = cleaned_df[column].fillna("Not Applicable")

In [30]:
cleaned_df[categorical_na_columns].isnull().sum()

Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Payment_Method                0
dtype: int64

In [31]:
date_time_match = (
    cleaned_df["Date"].dt.strftime("%H:%M:%S")
    == cleaned_df["Time"]
)

print("Rows where Date time matches Time:", date_time_match.sum())
print("Total rows:", len(cleaned_df))

Rows where Date time matches Time: 103024
Total rows: 103024

In [32]:
category_columns = [
    "Booking_Status",
    "Vehicle_Type",
    "Pickup_Location",
    "Drop_Location",
    "Payment_Method"
]

for column in category_columns:
    print(f"\n--- {column} ---")
    print(cleaned_df[column].value_counts(dropna=False).head(30))

--- Booking_Status ---
Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

--- Vehicle_Type ---
Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

--- Pickup_Location ---
Pickup_Location
Banashankari         2201
Yeshwanthpur         2139
RT Nagar             2135
Indiranagar          2133
Sahakar Nagar        2126
Basavanagudi         2120
Ramamurthy Nagar     2116
Vijayanagar          2113
Tumkur Road          2105
Cox Town             2100
Magadi Road          2099
BTM Layout           2091
Hennur               2090
Whitefield           2087
Mysore Road          2085
Nagarbhavi           2083
Kengeri              2083
Langford Town        2079
Hosur Road           2074
Kammanahalli         2071
Sarjapur Road        2070
Peenya               2069
Majestic             2067
Koramangala          2062
Hebbal               2058
KR Puram             2058
Malleshwaram         2058
MG Road              2048
Frazer Town          2048
Bannerghatta Road    2046
Name: count, dtype: int64

--- Drop_Location ---
Drop_Location
Peenya               2159
Mysore Road          2148
MG Road              2128
Hennur               2120
HSR Layout           2117
Sarjapur Road        2108
Koramangala          2105
Marathahalli         2104
Vijayanagar          2103
Hebbal               2097
BTM Layout           2096
Sahakar Nagar        2093
Bannerghatta Road    2091
RT Nagar             2089
Kadugodi             2088
JP Nagar             2088
Kengeri              2085
Jayanagar            2073
Hosur Road           2073
Banashankari         2072
Frazer Town          2070
Shivajinagar         2068
Majestic             2067
Kammanahalli         2067
Tumkur Road          2060
Langford Town        2059
Devanahalli          2055
Malleshwaram         2054
Magadi Road          2053
Hulimavu             2051
Name: count, dtype: int64

--- Payment_Method ---
Payment_Method
Not Applicable    39057
Cash              35022
UPI               25881
Credit Card        2435
Debit Card          629
Name: count, dtype: int64

In [33]:
cleaned_df = cleaned_df.drop(columns=["Time"])

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Rows: 103024
Columns: 18

In [34]:
text_columns = [
    "Booking_Status",
    "Vehicle_Type",
    "Pickup_Location",
    "Drop_Location",
    "Canceled_Rides_by_Customer",
    "Canceled_Rides_by_Driver",
    "Incomplete_Rides",
    "Incomplete_Rides_Reason",
    "Payment_Method"
]

for column in text_columns:
    whitespace_count = (
        cleaned_df[column].astype(str)
        .ne(cleaned_df[column].astype(str).str.strip())
        .sum()
    )

    print(f"{column}: {whitespace_count} values with extra spaces")

Booking_Status: 0 values with extra spaces
Vehicle_Type: 0 values with extra spaces
Pickup_Location: 0 values with extra spaces
Drop_Location: 0 values with extra spaces
Canceled_Rides_by_Customer: 0 values with extra spaces
Canceled_Rides_by_Driver: 0 values with extra spaces
Incomplete_Rides: 0 values with extra spaces
Incomplete_Rides_Reason: 0 values with extra spaces
Payment_Method: 0 values with extra spaces

In [35]:
print("Total rides with 0 distance:")
print((cleaned_df["Ride_Distance"] == 0).sum())

print("\nSuccessful rides with 0 distance:")
print(
    (
        (cleaned_df["Ride_Distance"] == 0) &
        (cleaned_df["Booking_Status"] == "Success")
    ).sum()
)

print("\nNon-successful rides with 0 distance:")
print(
    (
        (cleaned_df["Ride_Distance"] == 0) &
        (cleaned_df["Booking_Status"] != "Success")
    ).sum()
)

Total rides with 0 distance:
39057

Successful rides with 0 distance:
0

Non-successful rides with 0 distance:
39057

In [36]:
print("V_TAT outside expected positive range:")
print(((cleaned_df["V_TAT"].notna()) & (cleaned_df["V_TAT"] <= 0)).sum())

print("\nC_TAT outside expected positive range:")
print(((cleaned_df["C_TAT"].notna()) & (cleaned_df["C_TAT"] <= 0)).sum())

print("\nBooking Value <= 0:")
print((cleaned_df["Booking_Value"] <= 0).sum())

print("\nRide Distance < 0:")
print((cleaned_df["Ride_Distance"] < 0).sum())

print("\nDriver Rating outside 3-5:")
print(
    (
        cleaned_df["Driver_Ratings"].notna() &
        ~cleaned_df["Driver_Ratings"].between(3, 5)
    ).sum()
)

print("\nCustomer Rating outside 3-5:")
print(
    (
        cleaned_df["Customer_Rating"].notna() &
        ~cleaned_df["Customer_Rating"].between(3, 5)
    ).sum()
)

V_TAT outside expected positive range:
0

C_TAT outside expected positive range:
0

Booking Value <= 0:
0

Ride Distance < 0:
0

Driver Rating outside 3-5:
0

Customer Rating outside 3-5:
0

In [37]:
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

print("\nColumn names:")
print(cleaned_df.columns.tolist())

print("\nMissing values:")
print(cleaned_df.isnull().sum())

Rows: 103024
Columns: 18

Column names:
['Date', 'Booking_ID', 'Booking_Status', 'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT', 'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value', 'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating']

Missing values:
Date                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

In [38]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

In [39]:
cleaned_df.to_csv(
    "../data/cleaned/cleaned_bookings.csv",
    index=False
)

In [40]:
print("Cleaned dataset saved successfully.")
print("Rows:", len(cleaned_df))
print("Columns:", len(cleaned_df.columns))

Cleaned dataset saved successfully.
Rows: 103024
Columns: 18

In [41]:
raw_df = pd.read_csv("../data/raw/Bookings.csv")

print("Raw dataset:")
print("Rows:", raw_df.shape[0])
print("Columns:", raw_df.shape[1])

print("\nCleaned dataset:")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Raw dataset:
Rows: 103024
Columns: 21

Cleaned dataset:
Rows: 103024
Columns: 18